services:
    _defaults:
        autowire: true
        public: true

    chaplean.business_days_factory:
        class: Chaplean\Bundle\BusinessDaysBundle\Factory\BusinessFactory

    # Class kept even if we use a factory because of this symfony message:
    #      Please add the class to service "chaplean.business_days" even if
    #      it is constructed by a factory since we might need to add method
    #      calls based on compile-time checks
    chaplean.business_days:
        class: Chaplean\Bundle\BusinessDaysBundle\Business\Business
        factory: ['@chaplean.business_days_factory', createBusiness]
        arguments: ['%locale%']
